adobe/cla-bot

checker/checker.js
See https://github.com/adobe/cla-bot-playground/pull/28/checks?check_run_id=46164991 to see it in action
=> added comments to close and re-open PR once signed

.gitignore, .travis.yml, README.md, checker/checker.js, deploy.sh, lookup/lookup.js, setgithubcheck/setgithubcheck.js, utils.js
Please review!
I guess we won't be able to see if it works until we merge into master 😄
=> Continuous Deployment via Travis

checker/checker.js, checker/test.js
(also added a test for this)
This closes #15.
If you are cool with it merge away.
=> 🐛✅ trigger checker action only on open pull request events

README.md
This closes #8.
Feel free to merge upon approval.
=> 📝 documenting how to set up the github app

checker/checker.js
FYI I need to run but I want to add some more tests here first before merging - so don't merge yet! In the mean time y'all can review the logic tweaks.
- makes status codes explicit
- use `includes` instead of `indexOf`
- ensure `action_required` returns a promise, and leverage the promise as per usual promise handling inside `checker.main`
FYI @stevengill, @hirenoble 
@hirenoble, things to note:
It is key that `action_required` _returns_ a promise. We can then leverage it properly within a separate promise chain. So inside a separate promise chain, we can use `return action_required()` and then expect that whatever `action_required` returns within its _own_ promise chain, we will receive inside ours. The following statements are now equivalent:
```javascript
// Keep deepening the …
```
=> 🐛 [checker] promise tweaks

checker/checker.js
=> Revert "🐛 [checker] promise tweaks"

checker/checker.js
I have tested this code and it works well in both the scenario. i.e. works well in action_required and CLA Signed case and returning valid response for checker action.
Meanwhile we can deploy this code until we implement the async/await solution.
=> Fixing empty response issue

checker/checker.js, test/checker.test.js
=> 🐛 cla bot should ignore bot events

checker/checker.js, test/checker.test.js
for PRs issued to adobe-owned orgs that are not github.com/adobe, additionally check for public membership in github.com/adobe.
This fixes #44.
FYI @raducotescu this should fix the issue you saw in https://github.com/AdobeDocs/experience-manager-htl.en/pull/2
=> ✨ additional check for github.com/adobe public membership

checker/checker.js
Added handbook link in response
=> Issue #48: added self serve instructions in response for adobe employees

checker/checker.js, test/checker.test.js
=> 🤖✅ approve bot accounts

.gitignore, .travis.yml, checker/package-lock.json, deploy.sh, lookup/package-lock.json, package-lock.json, package.json, setgithubcheck/package-lock.json, test/integration/http.test.js, test/integration/jasmine.json, test/unit/checker.test.js, test/unit/jasmine.json, test/unit/lookup.test.js, test/unit/setgithubcheck.test.js
- checker smoke tests over http
- locking in package lock json.
- expanding deploy script to deploy to a stage action as well as prod actions.
- integrating integration testing and env handling in deploy script into travis run.
=> ✅ adding integration tests

.travis.yml, checker/checker.js, deploy.sh, package-lock.json, package.json, test/integration/github.test.js, utils.js
Still a work in progress
This closes #42 
TODO:
=> end-to-end github-app-based tests

checker/checker.js, test/integration/github.test.js
=> ✅ adding tests for private repo support

checker/checker.js
Pushing @prashcr's PR from #72 to the origin so that full integration tests can run.
This closes #47.
=> Prashcr doc patch

package-lock.json, package.json
Hat tip to @dlemstra for the PR! If the tests pass I will merge  this in and it'll get  automatically deployed.
=> Ran npm audit fix to update package with 1 high severity vulnerability.

package.json, signwebhook/signwebhook.js
=> chore: 🤖 lint signwebhook dir

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
Added documentation about unit and integration tests in this repo to `CONTRIBUTING.md`
Added PR template, demonstrated here
Closes https://github.com/adobe/cla-bot/issues/65
=> Update contribution guidelines and PR template

lookup/lookup.js, test/unit/lookup.test.js
=> 🔙 reverting parallelization work to fix signwebhook

signwebhook/signwebhook.js
I added the identified usernames to the error text for the `signwebhook` action. As far as I could tell, all other relevant information is already provided by the existing error messages. Let me know if you find anything else that's important to add.
Closes #86
=> Add origin details

.codecov.yml, .gitignore, .nycrc.json, .travis.yml, package-lock.json, package.json
reporting unit test code coverage using `istanbul` & `codecov` 
Done:
Notes:
- don't forget to add `CODECOV_TOKEN` environment variable in travis settings 
closes #98
=> chore: 🤖 add unit test code coverage reporting

README.md, test/integration/github.test.js
=> updating public test repo for magento

checker/checker.js, test/integration/github.test.js, test/unit/checker.test.js
If CLA app installed on "magento" org, everyone should sign CLA.
[DEVX-311](https://jira.corp.adobe.com/browse/DEVX-311): Update Adobe CLA bot
=> DEVX-311: Update Adobe CLA bot

checker/checker.js
Removed confusing statement in the error message when CLA check fails.
Closes https://github.com/adobe/cla-bot/issues/128
=> adobe/cla-bot#128: Update error message when cla check fails for Magento org
